In [1]:
def addNumbers(a,b):
    return a+b;

In [2]:
addNumbers(12,78)

90

In [3]:
x=[1,'add',2,'sub']

In [4]:
type(x)

list

In [5]:
x.append(3.33)


In [6]:
x

[1, 'add', 2, 'sub', 3.33]

In [7]:
for item in x:
    print(item)

1
add
2
sub
3.33


In [8]:
[print(i) for i in x]

1
add
2
sub
3.33


[None, None, None, None, None]

In [9]:
y=(1,2,3,4)    

In [10]:

type(y)

tuple

In [11]:
(9)

9

In [12]:
i=0
while(i<len(x)):
    print(x[i])
    i=i+1

1
add
2
sub
3.33


In [13]:
a={1:0,5:1,4:2}
a[5]

1

In [14]:
x=[1,2,3,4,5]
target=9
a={}

for i in range(len(x)):
    num=x[i]
    pair=target-num
    if(pair in a):
         print(a[pair],i)
    else:
        a[num]=i



3 4


In [15]:
zert='Mele ne Michael'
zert[:]

'Mele ne Michael'

In [16]:
zert[0:5]

'Mele '

In [17]:
zert[-1]

'l'

In [18]:
zert[:-2]

'Mele ne Micha'

In [19]:
zert[-7:-2]

'Micha'

### dictionary

In [20]:
item_j={0:"haris",1:"kari",10:"abhi"}

In [21]:
for i,j in item_j.items():
    print(str(i)+" "+str(j))
    

0 haris
1 kari
10 abhi


### set
it returns unique {} of items with sorting.

In [22]:
tuppy={'pel','vach','chel'}
pehlu,vachhe,chellu=tuppy

In [23]:
pehlu

'vach'

In [24]:
vachhe

'pel'

In [25]:
chellu

'chel'

In [26]:
puppy=('akkad','bakkad','bambe')
fir,tune,pyaar=puppy

In [27]:
fir

'akkad'

In [28]:
tune

'bakkad'

In [29]:
pyaar

'bambe'

In [30]:
per_maru={
    'name': 'harishya',
    'kam' : 'student',
    'umar' : 26
}

maru_statement='{} ni umar {} thai ne haji pan e ek {} che'
print(maru_statement.format(per_maru['name'],
                            per_maru['umar'],
                            per_maru['kam']
                                ))

harishya ni umar 26 thai ne haji pan e ek student che


## Data Files and statistics

In [31]:
import csv
%precision 2
with open('mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))

In [32]:
mpg[:]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [33]:
mpg[:3] ###gives three entries

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [34]:
mpg[:]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [35]:
type(mpg)

list

In [36]:
mpg[3:]

[OrderedDict([('', '4'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'auto(av)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '30'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '5'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2.8'),
              ('year', '1999'),
              ('cyl', '6'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '16'),
              ('hwy', '26'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '6'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2.8'),
              ('year', '1999'),
              ('cyl', '6'),
              ('trans', 'manual(m5)'),
              ('drv', '

In [37]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

### average mpg in city

In [38]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

### average mpg in highway

In [39]:
[float(h['hwy']) for h in mpg]
sum(float(h['hwy']) for h in mpg) / len(mpg)

23.44

### average mpg group by the cylinders the vehicle has

In [40]:
cylinders= set((d['cyl']) for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [41]:
ctyMpgByCyl=[]
for c in cylinders:
    cityMpg=0
    count=0
    for d in mpg:
        if (d['cyl']) == c:
            cityMpg += float(d['cty'])
            count+=1
    ctyMpgByCyl.append((c,cityMpg / count)) 

ctyMpgByCyl.sort(key=lambda x: x[0]) ## sorting data with index first in tuple ie cylinder
ctyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

### average mpg gby diff vehicle classes 

In [42]:
vClass=set((dt['class'])for dt in mpg)
vClass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [43]:
vH=[]
for v in vClass:
    sumH=0
    count = 0
    for d in mpg:
        if d['class']==v :
            sumH += float(d['hwy'])
            count += 1
    vH.append((v,sumH / count))
vH.sort(key=lambda x: x[1])   ## sorting data with tuple 2 i.e with average
vH

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

### iterating over dictonary if element of tuple present in dictionary.

In [44]:
d={1:2,3:4,5:6,7:8}
## need subset of d with keys 1 to 5
l=(1,5)
[{k:d[k]} for k in l if k in d]

[{1: 2}, {5: 6}]

In [45]:
type(d)

dict

### date and times

In [46]:
import datetime as dt
import time as tm

In [47]:
tm.time() # since epoch i.e. 1970

1581245290.38

In [48]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 2, 9, 10, 48, 10, 395070)

In [49]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour,dtnow.minute, dtnow.second

(2020, 2, 9, 10, 48, 10)

In [50]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(100)

In [51]:
today = dt.date.today()

In [52]:
today-delta

datetime.date(2019, 11, 1)

In [53]:
today>today-delta

True

### functions and map()

In [54]:
class Myself:
    college = 'Nirma Institute of Technology'
    def name(self,name1):
        self.name=name1
    def state(self,state1):
        self.state=state1
        

In [55]:
funcall= Myself()
funcall.name('Harish')
funcall.state('Gujarat')
print('{} is a student of {} which is located in {} state'.format(funcall.name, funcall.college, funcall.state))

Harish is a student of Nirma Institute of Technology which is located in Gujarat state


In [56]:
x1=[1,3,5,7,9,11]
x2=[0,2,9,6,8,12]
x=map(min,x1,x2) ## map() by default stores objects, to access the elements you need to iterate to stored objects.
a=[]

In [57]:
[i for i in x] #iteration through the map(), you can even use map on list and tuple combined.

[0, 2, 5, 6, 8, 11]

Here is a list of faculty teaching this MOOC. Can you write a function and apply it using map() to get a list of all faculty titles and last names (e.g. ['Dr. Brooks', 'Dr. Collins-Thompson', …]) ?

In [58]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    first = person.split()[0]
    last = person.split()[-1]
    return ('{} {}'.format(first,last))
#     return None


list(map(split_title_and_name,people))
# split_title_and_name(people)


['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [59]:
a

[]

### Lambda
return of lambda is function reference

In [60]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x : x.split()[0] + ' ' + x.split()[-1])( person ))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda x:x.split()[0] + ' ' + x.split()[-1],people))

True
True
True
True


True

####  using list comprehension

In [61]:
mylist=[]

[mylist.append(n) for n in list(range(0,10)) if n % 2==0]

[None, None, None, None, None]

In [62]:
mylist

[0, 2, 4, 6, 8]

#### using for loop

In [63]:
mylist=[]
for n in range(0,10):
    if n % 2 == 0:
        mylist.append(n)
mylist

[0, 2, 4, 6, 8]

#### using while loop

In [64]:
mylist=[]
n = 0
while n < 10:
    if n % 2 == 0 :
        mylist.append(n)
    n+=1
mylist

[0, 2, 4, 6, 8]

#### other way of list comprehension

In [65]:
mylist= [n for n in range(0,10) if n % 2 == 0]
mylist

[0, 2, 4, 6, 8]

In [66]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range(10) for j in range(10) ]

True

Here’s a harder question which brings a few things together.

Many organizations have user ids which are constrained in some way. Imagine you work at an internet service provider and the user ids are all two letters followed by two numbers (e.g. aa49). Your task at such an organization might be to hold a record on the billing activity for each possible user.

Write an initialization line as a single list comprehension which creates a list of all possible user ids. Assume the letters are all lower case.

In [67]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]
# correct_answer == answer

answer

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49',
 'aa50',
 'aa51',
 'aa52',
 'aa53',
 'aa54',
 'aa55',
 'aa56',
 'aa57',
 'aa58',
 'aa59',
 'aa60',
 'aa61',
 'aa62',
 'aa63',
 'aa64',
 'aa65',
 'aa66',
 'aa67',
 'aa68',
 'aa69',
 'aa70',
 'aa71',
 'aa72',
 'aa73',
 'aa74',
 'aa75',
 'aa76',
 'aa77',
 'aa78',
 'aa79',
 'aa80',
 'aa81',
 'aa82',
 'aa83',
 'aa84',
 'aa85',
 'aa86',
 'aa87',
 'aa88',
 'aa89',
 'aa90',
 'aa91',
 'aa92',
 'aa93',
 'aa94',
 'aa95',
 'aa96',
 'aa97',
 'aa98',
 'aa99',
 'ab00',
 'ab01',
 'ab02',
 'ab03',
 'ab04',
 'ab05',
 'ab06',
 'ab07',
 'ab08',
 'ab09',
 'ab10',
 

In [68]:
len(answer)

67600

In [69]:
answer[:10]

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09']

In [70]:
answer[7:10]

['aa07', 'aa08', 'aa09']

# Numpy

In [71]:
import numpy as np

In [72]:
mylist=[1,2,3,4,5]
x= np.array(mylist)
x

array([1, 2, 3, 4, 5])

In [73]:
y = np.array([3,5,6,7,8])
y

array([3, 5, 6, 7, 8])

In [74]:
m = np.array([[1,3,5,7],[2,4,6,8]]) #multidimension
m

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [75]:
n = np.arange(0,20,2)   # specify the start,end and steps required between the interval
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
n.shape

(10,)

In [77]:
n = n.reshape(2,5) #dimension of array
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [78]:
lin= np.linspace(0,4,10)  # start,end and total numbers required, it will implicitly separate the interval.
lin

array([ 0.        ,  0.44444444,  0.88888889,  1.33333333,  1.77777778,
        2.22222222,  2.66666667,  3.11111111,  3.55555556,  4.        ])

In [79]:
lin.shape

(10,)

In [80]:
lin.resize(2,5) #inplace resize of a numpy array
lin

array([[ 0.        ,  0.44444444,  0.88888889,  1.33333333,  1.77777778],
       [ 2.22222222,  2.66666667,  3.11111111,  3.55555556,  4.        ]])

In [81]:
lin.shape

(2, 5)

In [82]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [83]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [84]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [85]:
np.diag(y)

array([[3, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 8]])

In [86]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [87]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [88]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [89]:
p2=np.vstack([p,2*p]) ## appending  to rows
p2

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [90]:
p2.shape 

(4, 3)

In [91]:
p3 =  np.hstack([p,4*p]) ## appending to columns
p3

array([[1, 1, 1, 4, 4, 4],
       [1, 1, 1, 4, 4, 4]])

In [92]:
p3.shape

(2, 6)

In [93]:
x,y

(array([1, 2, 3, 4, 5]), array([3, 5, 6, 7, 8]))

In [94]:
x*y

array([ 3, 10, 18, 28, 40])

In [95]:
x**y

array([     1,     32,    729,  16384, 390625])

In [96]:
x**4

array([  1,  16,  81, 256, 625])

In [97]:
5**8

390625

In [98]:
np.dot(x,y)

99

In [99]:
x.dot(y)

99

In [100]:
z= np.array([y,y**2])
z

array([[ 3,  5,  6,  7,  8],
       [ 9, 25, 36, 49, 64]])

In [101]:
z.shape

(2, 5)

In [102]:
z.T # not inplace


array([[ 3,  9],
       [ 5, 25],
       [ 6, 36],
       [ 7, 49],
       [ 8, 64]])

In [103]:
z.shape

(2, 5)

In [104]:
#changing type of array
z=z.astype('f')
z.dtype

dtype('float32')

In [105]:
a=np.array([-2,-4,2,3,5])

In [106]:
a.sum()

4

In [107]:
a.min()

-4

In [108]:
a.max()

5

In [109]:
a.mean()

0.80

In [110]:
a.std()

3.31

In [111]:
# for indexing of max or min use argmax or argmin
a.argmax()


4

In [112]:
a.argmin()

1

### indexing or slicing

In [113]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [114]:
s[0],s[4],s[0:3] #start and ending with colon.

(0, 16, array([0, 1, 4]))

In [115]:
s[0::3] # start,end,with steps to jump

array([  0,   9,  36,  81, 144])

In [116]:
s[0:10:2]   #during slicing don't include menioned ending element example here 10 index is 100 but don't include it
            # but include the starting element here 0 in list has index 0 which is the start of slice.

array([ 0,  4, 16, 36, 64])

In [117]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [118]:
r[2,2]

14

In [119]:
r[2:,]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [123]:
r[2,:] ##for printing only single row

array([12, 13, 14, 15, 16, 17])

In [124]:
r[:,3] ##for printing only single column

array([ 3,  9, 15, 21, 27, 33])

In [125]:
r[3,3:6]

array([21, 22, 23])

In [126]:
r>30

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True]], dtype=bool)

In [127]:
r[r>30]

array([31, 32, 33, 34, 35])

In [129]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [130]:
r2=r[:3,:3] #copying data
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [131]:
r2[:]=0

In [132]:
r #main array got changed

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [134]:
# so in order to change an array without affecting the previous values make a copy of it and perform operations in the copy
r3=r.copy()
r3

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [138]:
r4=r3[:3,:3]
r4[:]=99
r3 #change in copied array

array([[99, 99, 99,  3,  4,  5],
       [99, 99, 99,  9, 10, 11],
       [99, 99, 99, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [139]:
r #original array remains intact

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [164]:
r[2:4,2:4]

array([[ 0, 15],
       [20, 21]])

### iterating on arrays

In [140]:
test = np.random.randint(0,10,(4,3))
test

array([[8, 0, 3],
       [3, 5, 5],
       [4, 5, 9],
       [9, 7, 8]])

In [142]:
for row in test:
    print(row)

[8 0 3]
[3 5 5]
[4 5 9]
[9 7 8]


In [146]:
for i in range(len(test)):
    print(test[i])

[8 0 3]
[3 5 5]
[4 5 9]
[9 7 8]


In [145]:
mat=[row for row in test]
mat

[array([8, 0, 3]), array([3, 5, 5]), array([4, 5, 9]), array([9, 7, 8])]

In [148]:
for i,row in enumerate(test): #enumerate returns the index along with value of the row
    print('row',i,'is',row)
    print('------------------')
    

row 0 is [8 0 3]
------------------
row 1 is [3 5 5]
------------------
row 2 is [4 5 9]
------------------
row 3 is [9 7 8]
------------------


In [149]:
#iterating on more than one array use zip
test2 = test**2
test2

array([[64,  0,  9],
       [ 9, 25, 25],
       [16, 25, 81],
       [81, 49, 64]])

In [151]:
for i,j in zip(test,test2):
    print('sum of',i,'and',j,'is',i+j)

sum of [8 0 3] and [64  0  9] is [72  0 12]
sum of [3 5 5] and [ 9 25 25] is [12 30 30]
sum of [4 5 9] and [16 25 81] is [20 30 90]
sum of [9 7 8] and [81 49 64] is [90 56 72]


In [161]:
type(lambda x:x*y)

function

In [163]:
['a','b']+[1,2]

['a', 'b', 1, 2]